<?php
/**
 * Created by haph on 12/19/15
 */

/**
 * @file
 * @reviewed by Ha
 * @date Feb 04, 2016
 */

// node type
define('BUNDLE_BLOG_STANDARD', 'blog_standard');
define('BUNDLE_BLOG_GALLERY', 'blog_gallery');
define('BUNDLE_BLOG_VIDEO', 'blog_video');
define('BUNDLE_BLOG_AUDIO', 'blog_audio');
define('BUNDLE_COURSES', 'courses');
define('BUNDLE_EVENTS', 'events');

// constant pager
define('PAGER_EVENT', 8);
define('PAGER_COURSES', 2);
define('PAGER_BLOG_LIST_1', 4);
define('PAGER_BLOG_LIST_2', 5);
define('PAGER_PROFESSORS_LIST', 6);

// others
define('BEAN_QUOTE', 79);

// block
define('RELATED_POSTS_BLOG', 3);
